require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'BaseProject' do
  use_unimodules!
  config = use_native_modules!

  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  
  # use_react_native!(:path => config["reactNativePath"])
  use_react_native!(
    	    :path => config[:reactNativePath],
    	    # to enable hermes on iOS, change `false` to `true` and then install pods
    	    :hermes_enabled => true
  )

  target 'BaseProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
#   # you should disable these next few lines.
#   use_flipper!
#   post_install do |installer|
#     flipper_post_install(installer)
#   end
# end

# target 'BaseProject-tvOS' do
#   # Pods for BaseProject-tvOS

#   target 'BaseProject-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
# you should disable the next line.
use_flipper!()
post_install do |installer|
react_native_post_install(installer)
  end
end
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end