export const SEARCH_ACTION = {
  SEARCH_FETCH_SUCCEEDED: "SEARCH_FETCH_SUCCEEDED",
  SEARCH_FETCH_FAILED: "SEARCH_FETCH_FAILED",
  SEARCH_FETCH_REQUESTED: "SEARCH_FETCH_REQUESTED",
}

export const DIALOG_STATE = {
  CHANGE_CONTENT: "CHANGE_CONTENT",
  CHANGE_CONTENT_CONFIRM: "CHANGE_CONTENT_CONFIRM",
}

export const REFRESH_LIST_ACTION = {
  REFRESH_LIST: "REFRESH_LIST",
}
