export const USER_ACTION = {
  USER_FETCH_SUCCEEDED: "USER_FETCH_SUCCEEDED",
  USER_FETCH_FAILED: "USER_FETCH_FAILED",
  USER_FETCH_REQUESTED: "USER_FETCH_REQUESTED",
}

export const DIALOG_STATE = {
  CHANGE_CONTENT: "CHANGE_CONTENT",
  CHANGE_CONTENT_CONFIRM: "CHANGE_CONTENT_CONFIRM",
}

export const INIT_ACTION = {
  INIT_STATE_REQUESTED: "INIT_STATE_REQUESTED",
  UPDATE_INIT_STATE: "UPDATE_INIT_STATE",
  INIT_STATE_REQUESTED_SUCCEEDED: "INIT_STATE_REQUESTED_SUCCEEDED",
  INIT_STATE_REQUESTED_FAILED: "INIT_STATE_REQUESTED_FAILED",
}

export const GET_AUTHORITY_INFO_ACTION = {
  GET_AUTHORITY_INFO_SUCCEEDED: "GET_AUTHORITY_INFO_SUCCEEDED",
  GET_AUTHORITY_INFO_FAILED: "GET_AUTHORITY_INFO_FAILED",
  GET_AUTHORITY_INFO_REQUESTED: "GET_AUTHORITY_INFO_REQUESTED",
}

export const REFRESH_LIST_ACTION = {
  REFRESH_LIST: "REFRESH_LIST",
}
