export const USER_ACTION = {
  USER_FETCH_SUCCEEDED: "USER_FETCH_SUCCEEDED",
  USER_FETCH_FAILED: "USER_FETCH_FAILED",
  USER_FETCH_REQUESTED: "USER_FETCH_REQUESTED",
  REFRESH_ACTIVITY: "REFRESH_ACTIVITY",
}

export const DIALOG_STATE = {
  CHANGE_CONTENT: "CHANGE_CONTENT",
  CHANGE_CONTENT_CONFIRM: "CHANGE_CONTENT_CONFIRM",
}
